---
# tasks file for backend-update
- name: Delete backend dir
  file:
    path: '{{ WORKERS_BIN }}'
    state: absent

- name: Create backend dir
  file:
    path: '{{ WORKERS_BIN }}'
    state: directory
    recurse: yes

- name: Upload backend files
  synchronize:
    src: '{{ SRC_DIR }}'
    dest: '{{ WORKERS_BIN }}'
  register: copyfiles

- name: Install "typescript" node.js package globally.
  npm:
    name: typescript
    global: yes
  become: yes

- name: Install packages based on package.json
  shell: npm i
  args:
    chdir: '{{ WORKERS_BIN }}'

- name: Build code
  shell: npm run build
  args:
   chdir: '{{ WORKERS_BIN }}'

- name: Copy or generate app.json file
  template:
    src: ./app.json.j2
    dest: '{{ WORKERS_BIN }}/app.json'

- name: Copy or generate quest env file
  template:
    src: ./{{ quest_env }}.j2
    dest: '{{ WORKERS_BIN }}/{{ quest_env }}'

- name: Copy or generate quest-factory env file
  template:
    src: ./{{ quest_factory_env }}.j2
    dest: '{{ WORKERS_BIN }}/{{ quest_factory_env }}'

- name: Copy or generate fetcher env file
  template:
    src: ./{{ fetcher_env }}.j2
    dest: '{{ WORKERS_BIN }}/{{ fetcher_env }}'

- name: Copy or generate broker env file
  template:
    src: ./{{ broker_env }}.j2
    dest: '{{ WORKERS_BIN }}/{{ broker_env }}'

- name: Start backend process
  shell: pm2 reload app.json
  args:
   chdir: '{{ WORKERS_BIN }}'

- name: Saving current process list
  shell: pm2 save
  args:
   chdir: '{{ WORKERS_BIN }}'
