name: deploy-worker

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[update]')"

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2.4.0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa

      - name: Install npm dependencies
        run: npm i

      - name: Run build task
        run: npm run build

  deploy-master:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2.4.0

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} ansible_port=${{ secrets.REMOTE_PORT }} \

          DB_LINK=${{ secrets.PROD_DB_LINK }} \

          NOTIFICATION_MESSAGE_BROKER_LINK=${{ secrets.PROD_NOTIFICATION_MESSAGE_BROKER_LINK }} \

          BRIDGE_DEBUG=${{ secrets.secrets.PROD_BRIDGE_DEBUG }} \
          BRIDGE_ETH_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_BRIDGE_ETH_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_ETH_MAINNETWORK_CONTRACT=${{ secrets.PROD_BRIDGE_ETH_MAINNETWORK_CONTRACT }} \
          BRIDGE_ETH_MAINNETWORK_WEBSOCKET_PROVIDER=${{ secrets.PROD_BRIDGE_ETH_MAINNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_BSC_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_BRIDGE_BSC_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_BSC_MAINNETWORK_CONTRACT=${{ secrets.PROD_BRIDGE_BSC_MAINNETWORK_CONTRACT }} \
          BRIDGE_BSC_MAINNETWORK_WEBSOCKET_PROVIDER=${{ secrets.PROD_BRIDGE_BSC_MAINNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_RINKEBY_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_BRIDGE_RINKEBY_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_RINKEBY_TESTNETWORK_CONTRACT=${{ secrets.PROD_BRIDGE_RINKEBY_TESTNETWORK_CONTRACT }} \
          BRIDGE_RINKEBY_TESTNETWORK_WEBSOCKET_PROVIDER=${{ secrets.PROD_BRIDGE_RINKEBY_TESTNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_BSC_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_BRIDGE_BSC_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_BSC_TESTNETWORK_CONTRACT=${{ secrets.PROD_BRIDGE_BSC_TESTNETWORK_CONTRACT }} \
          BRIDGE_BSC_TESTNETWORK_WEBSOCKET_PROVIDER=${{ secrets.PROD_BRIDGE_BSC_TESTNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_CONTRACT_PRIVAT_KEY=${{ secrets.PROD_BRIDGE_CONTRACT_PRIVAT_KEY }} \

          DAILY_LIQUIDITY_CONTRACT_ADDRESS=${{ secrets.PROD_DAILY_LIQUIDITY_CONTRACT_ADDRESS }} \
          DAILY_LIQUIDITY_WEBSOCKET_PROVIDER=${{ secrets.PROD_DAILY_LIQUIDITY_WEBSOCKET_PROVIDER }} \

          PROPOSAL_DEBUG=${{ secrets.PROD_PROPOSAL_DEBUG }} \
          PROPOSAL_RINKEBY_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_PROPOSAL_RINKEBY_PARSE_EVENTS_FROM_HEIGHT }} \
          PROPOSAL_RINKEBY_CONTRACT=${{ secrets.PROD_PROPOSAL_RINKEBY_CONTRACT }} \
          PROPOSAL_RINKEBY_WEBSOCKET_PROVIDER=${{ secrets.PROD_PROPOSAL_RINKEBY_WEBSOCKET_PROVIDER }} \

          WQT_WBNB_CONTRACT_ADDRESS=${{ secrets.PROD_WQT_WBNB_CONTRACT_ADDRESS }} \
          WQT_WBNB_WEBSOCKET_PROVIDER=${{ secrets.PROD_WQT_WBNB_WEBSOCKET_PROVIDER }} \
          WQT_WBNB_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_WQT_WBNB_PARSE_EVENTS_FROM_HEIGHT }} \

          PENSION_FUND_CONTRACT_ADDRESS=${{ secrets.PROD_PENSION_FUND_CONTRACT_ADDRESS }} \
          PENSION_FUND_WEBSOCKET_PROVIDER=${{ secrets.PROD_PENSION_FUND_WEBSOCKET_PROVIDER }} \
          PENSION_FUND_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.PROD_PENSION_FUND_PARSE_EVENTS_FROM_HEIGHT }} \

          BACKEND_BIN=${{ secrets.PROD_BACKEND_BIN }} \

          PM2_BRIDGE_WORKER_NAME=${{ secrets.PROD_PM2_BRIDGE_WORKER_NAME }} \
          PM2_LIQUIDITY_WORKER_NAME=${{ secrets.PROD_PM2_LIQUIDITY_WORKER_NAME }} \
          PM2_PROPOSAL_WORKER_NAME=${{ secrets.PROD_PM2_PROPOSAL_WORKER_NAME }} \
          PM2_WQT_WBNB_WORKER_NAME=${{ secrets.PROD_PM2_WQT_WBNB_WORKER_NAME }} \
          PM2_PENSION_FUND_WORKER_NAME=${{ secrets.PROD_PM2_PENSION_FUND_WORKER_NAME }}
          SRC_DIR=${{ github.workspace }}/" backend-update.yml;

  deploy-develop:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [build]

    steps:
      - name: Copy code files to container
        uses: actions/checkout@v2.4.0

      - name: Environment preparation
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          chmod -R go= ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SSH_KEY }}" >> ~/.ssh/id_rsa
          sudo apt-add-repository -y -u ppa:ansible/ansible
          sudo apt-get install -y rsync
          sudo apt-get install -y ansible

      - name: Deploy to Server
        run: |
          chmod 700 ci-scripts
          cd ci-scripts
          ansible-playbook -i "${{ secrets.REMOTE_HOST }}" -e "ansible_user=${{ secrets.REMOTE_USER }} ansible_port=${{ secrets.REMOTE_PORT }} \

          DB_LINK=${{ secrets.DEV_DB_LINK }} \

          NOTIFICATION_MESSAGE_BROKER_LINK=${{ secrets.DEV_NOTIFICATION_MESSAGE_BROKER_LINK }} \

          BRIDGE_DEBUG=${{ secrets.secrets.DEV_BRIDGE_DEBUG }} \
          BRIDGE_ETH_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_BRIDGE_ETH_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_ETH_MAINNETWORK_CONTRACT=${{ secrets.DEV_BRIDGE_ETH_MAINNETWORK_CONTRACT }} \
          BRIDGE_ETH_MAINNETWORK_WEBSOCKET_PROVIDER=${{ secrets.DEV_BRIDGE_ETH_MAINNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_BSC_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_BRIDGE_BSC_MAINNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_BSC_MAINNETWORK_CONTRACT=${{ secrets.DEV_BRIDGE_BSC_MAINNETWORK_CONTRACT }} \
          BRIDGE_BSC_MAINNETWORK_WEBSOCKET_PROVIDER=${{ secrets.DEV_BRIDGE_BSC_MAINNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_RINKEBY_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_BRIDGE_RINKEBY_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_RINKEBY_TESTNETWORK_CONTRACT=${{ secrets.DEV_BRIDGE_RINKEBY_TESTNETWORK_CONTRACT }} \
          BRIDGE_RINKEBY_TESTNETWORK_WEBSOCKET_PROVIDER=${{ secrets.DEV_BRIDGE_RINKEBY_TESTNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_BSC_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_BRIDGE_BSC_TESTNETWORK_PARSE_EVENTS_FROM_HEIGHT }} \
          BRIDGE_BSC_TESTNETWORK_CONTRACT=${{ secrets.DEV_BRIDGE_BSC_TESTNETWORK_CONTRACT }} \
          BRIDGE_BSC_TESTNETWORK_WEBSOCKET_PROVIDER=${{ secrets.DEV_BRIDGE_BSC_TESTNETWORK_WEBSOCKET_PROVIDER }} \
          BRIDGE_CONTRACT_PRIVAT_KEY=${{ secrets.DEV_BRIDGE_CONTRACT_PRIVAT_KEY }} \

          DAILY_LIQUIDITY_CONTRACT_ADDRESS=${{ secrets.DEV_DAILY_LIQUIDITY_CONTRACT_ADDRESS }} \
          DAILY_LIQUIDITY_WEBSOCKET_PROVIDER=${{ secrets.DEV_DAILY_LIQUIDITY_WEBSOCKET_PROVIDER }} \

          PROPOSAL_DEBUG=${{ secrets.DEV_PROPOSAL_DEBUG }} \
          PROPOSAL_RINKEBY_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_PROPOSAL_RINKEBY_PARSE_EVENTS_FROM_HEIGHT }} \
          PROPOSAL_RINKEBY_CONTRACT=${{ secrets.DEV_PROPOSAL_RINKEBY_CONTRACT }} \
          PROPOSAL_RINKEBY_WEBSOCKET_PROVIDER=${{ secrets.DEV_PROPOSAL_RINKEBY_WEBSOCKET_PROVIDER }} \

          WQT_WBNB_CONTRACT_ADDRESS=${{ secrets.DEV_WQT_WBNB_CONTRACT_ADDRESS }} \
          WQT_WBNB_WEBSOCKET_PROVIDER=${{ secrets.DEV_WQT_WBNB_WEBSOCKET_PROVIDER }} \
          WQT_WBNB_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_WQT_WBNB_PARSE_EVENTS_FROM_HEIGHT }} \

          PENSION_FUND_CONTRACT_ADDRESS=${{ secrets.DEV_PENSION_FUND_CONTRACT_ADDRESS }} \
          PENSION_FUND_WEBSOCKET_PROVIDER=${{ secrets.DEV_PENSION_FUND_WEBSOCKET_PROVIDER }} \
          PENSION_FUND_PARSE_EVENTS_FROM_HEIGHT=${{ secrets.DEV_PENSION_FUND_PARSE_EVENTS_FROM_HEIGHT }} \

          BACKEND_BIN=${{ secrets.DEV_BACKEND_BIN }} \

          PM2_BRIDGE_WORKER_NAME=${{ secrets.DEV_PM2_BRIDGE_WORKER_NAME }} \
          PM2_LIQUIDITY_WORKER_NAME=${{ secrets.DEV_PM2_LIQUIDITY_WORKER_NAME }} \
          PM2_PROPOSAL_WORKER_NAME=${{ secrets.DEV_PM2_PROPOSAL_WORKER_NAME }} \
          PM2_WQT_WBNB_WORKER_NAME=${{ secrets.DEV_PM2_WQT_WBNB_WORKER_NAME }} \
          PM2_PENSION_FUND_WORKER_NAME=${{ secrets.DEV_PM2_PENSION_FUND_WORKER_NAME }}

          SRC_DIR=${{ github.workspace }}/" backend-update.yml;
